spring:
  application:
    name: CentralBank
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false

  jwt:
    secret: ${JWT_SECRET}
    interBankSecret: ${INTERBANK_SECRET}
    accessTokenExpiration: 900 # 15 min
    refreshTokenExpiration: 604800 # 7 days


  bank:
    bankMasterSecret: ${BANK_MASTER_SECRET}


  mvc:
    servlet:
      path: /api



    